name: Enable workflows
on:
  schedule:
    - cron: '22 22 1 * *' # Monthly on the 1st at 22:22
  workflow_dispatch:

jobs:
  normalize_repos:
    runs-on: ubuntu-latest
    steps:

    # https://github.com/actions/setup-python
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv

    # https://github.com/actions/checkout
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ADMIN_GITHUB_TOKEN }}

    - name: Install app dependencies
      run: pipenv sync --system

    - name: Run script with token in env
      run: ./enable_workflows.py \
        ccos-scripts
      env:
        ADMIN_GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
